// src/types/AgentTypes.ts

/**
 * Represents who sent the message.
 */
export type MessageRole = 'user' | 'agent' | 'system';

/**
 * Represents a single message exchanged between the User and the Agent.
 */
export interface AgentMessage {
  /** Unique ID for this message */
  id: string;

  /** Role of the sender (user, agent, system) */
  role: MessageRole;

  /** The text content of the message */
  content: string;

  /**
   * Optional visual/design output URL
   * Example: an AI-generated image or layout.
   * This is optional for normal text responses.
   */
  visualOutputUrl?: string;
}

/**
 * Represents the raw structured response returned from the AI/Backend.
 */
export interface AgentResponse {
  /** The text response generated by the AI agent */
  message: string;

  /**
   * Optional design output (image / generated asset)
   * Example: https://cdn.yourapp.com/output/design123.png
   */
  designResultUrl?: string;
}

